# Generated by Django 3.2.11 on 2022-01-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapi', '0004_auto_20220130_0347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='supplier',
        ),
        migrations.AddField(
            model_name='inventory',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
