# Generated by Django 3.2.11 on 2022-01-30 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapi', '0007_inventory_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='supplier',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_id', to='inventoryapi.supplier'),
        ),
    ]
